name: service2
on:
  pull_request:

jobs:
  npm_test:
    name: npm test
    runs-on: ubuntu-latest
    if: ${{ false }}

    steps:
      - name: Pass
        run: echo ok

  docker_build:
    name: docker build
    runs-on: ubuntu-latest
    if: ${{ false }}

    steps:
      - name: Pass
        run: echo ok
